### ISSUE TITLE
Issue in Magento 2.1 

### ISSUE THREAD

**Issue by Sumayah90** [shopigo/magento2-extension-price-format#5]
Hi,

I faced this issue with Magento Commerce 2.1 in Compile process 

How can I fix it?

![screen shot 2018-11-15 at 12 47 07 am](https://user-images.githubusercontent.com/6193435/48515139-14a36080-e871-11e8-99aa-ebc374e1bf98.png)

Thanks

**Comment by shopigo** [comment]
Hi,

This extension is not officially compatible with Magento 2.1.
However, this issue was fixed in the last version of the extension (1.0.2) published today.

Thanks
